add and config rockspec
TSnake41/raylib-lua pull request #30
Opened 2024-12-24 18:27 UTC by APConduct

Everything Was able to be built on my Windows 11 machine, save for an unsigned int pointer I had to change an unsigned int pointer to a signed int pointer for it to make. I also added skeleton specifications for the project to be available on Luarocks.

2025-02-21 23:59 UTC, TSnake41 requested changes
I will take the raylua_loadFileData (in a separate commit) fix, but have some questions regarding the rockspec.

2025-02-21 23:59 UTC, TSnake41 commented on raylib-lua-0.1-1.rockspec
> +version = "0.1-1" -- Update version based on your binding's state
I would prefer to have it match the raylib version (+a subversion of the binding).

2025-02-21 23:59 UTC, TSnake41 commented on raylib-lua-0.1-1.rockspec
> +    "lua >= 5.1",
This binding wants `ffi` to work, you need to have LuaJIT, or at least `libffi`.
Looking at other luarocks libraries, there seem to be no way to specify it as a dependency, but we still need to tell the users that it is a requirement.

2025-02-21 23:59 UTC, TSnake41 commented on raylib-lua-0.1-1.rockspec
> +    }
raylib-lua build process is pretty spartan and doesn't fit well the luarocks default build process in its current form.
That could be okay, but you would likely need to change some bits and add a `install` target (perhaps make a separate makefile).
You don't need to add `libraries = { "raylib" }` as raylib is built as a part of raylib-lua build process.

The raylib.so/.dll support is still quite experimental, but should work alright as long as Lua 5.1 ABI stays the same.

2025-03-03 04:17 UTC, APConduct commented on raylib-lua-0.1-1.rockspec
> +version = "0.1-1" -- Update version based on your binding's state
like this?:
```lua
version = "5.5" -- raylib version
subversion = "4.5a" -- binding version
```

2025-03-03 09:53 UTC, TSnake41 commented on raylib-lua-0.1-1.rockspec
> +version = "0.1-1" -- Update version based on your binding's state
more something like
```version = "4.5-1```

2025-03-03 22:34 UTC, APConduct commented on raylib-lua-0.1-1.rockspec
> +    "lua >= 5.1",
supposedly you can put luajit in the dependencies but i can't seem to make it work, at least with homebrew and msys2 distributions of luarocks and luajit, but ill mess around with it and see if external configurations like your makefile example work.

2025-03-08 21:48 UTC, closed without merging